### PR TITLE
Fix tslint

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by huningxin** [comment]
@pinzhenx, PTAL.

**Comment by huningxin** [comment]
It also fix the tsc compile issue:
```
$ npm run build

> onnxjs@0.1.7 build /home/nhu/code/onnxjs
> tsc && node tools/build --build-wasm --build-bundle

lib/backends/webnn/graph-utils.ts:235:5 - error TS2322: Type 'Set<unknown>[]' is not assignable to type 'Set<number>[]'.
  Type 'Set<unknown>' is not assignable to type 'Set<number>'.
    Type 'unknown' is not assignable to type 'number'.

235     return result;
        ~~~~~~~~~~~~~~

lib/backends/webnn/graph-utils.ts:306:27 - error TS2345: Argument of type 'Set<unknown>' is not assignable to parameter of type 'Set<number>'.

306         inputIds: sortSet(inTensors),
                              ~~~~~~~~~

lib/backends/webnn/graph-utils.ts:307:28 - error TS2345: Argument of type 'Set<unknown>' is not assignable to parameter of type 'Set<number>'.

307         outputIds: sortSet(outTensors),
                               ~~~~~~~~~~


Found 3 errors.

```

**Comment by pinzhenx** [comment]
It's weird that the tslint didn't complain about the code format issues on my side.
Many thanks for the PR. It looks good to me.

**Comment by pinzhenx** [comment]
@huningxin  There's a line I forgot to uncomment before. It was used to suppress the error by the graph transformation. Now it can be safely uncommented.

**Comment by huningxin** [comment]
My npm installed version:
tslint@5.17.0
typescript@3.5.1

Are they root cause?

**Comment by huningxin** [comment]
> @huningxin There's a line I forgot to uncomment before. It was used to suppress the error by the graph transformation. Now it can be safely uncommented.

looks good. thanks.

**Comment by pinzhenx** [comment]
I figured out that it's simply because my old vscode couldn't recognize the workspace settings like `tslint.configFile`. After I updated the vscode, it works.

**Comment by huningxin** [comment]
Great.

**Pull request merged**
